# Generated by Django 3.2.7 on 2021-10-01 16:36

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_post_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='images/'),
        ),
    ]
