# Generated by Django 3.2.7 on 2021-10-04 18:55

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(300, 300)]),
        ),
    ]
