# Generated by Django 3.2.7 on 2021-10-06 16:17

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/', validators=[stdimage.validators.MinSizeValidator(300, 300)]),
        ),
    ]
